### ISSUE TITLE
Content feedback

### ISSUE THREAD

**Issue by lemkeb** [relayr/raw-data-downloader#1]
Introduction: 

- This is a public repo, so include more context here. Why did relayr make this?  What's in this repo? What's in the readme? Why InfluxDB? Why Grafana?
- This readme has nothing about using Grafana, yet Grafana is mentioned in the repo description.

Requirements:

- "Dashboard" should be capitalized.
- Include a link to the documentation for how to register a device.

Installation & Configuration:

- Improve the language:
	- "Ubuntu based"
	- "For install the Requests module"
	- "install with PIP the last version"
	- "For running the script you have just to browse . . ."
	- "on relayr dashboard"
	- "from when download the readings"
	- "creadted"
- Put the script output underneath the parameter descriptions.
- There is no information about what the script does or the History API. This makes me wonder what the purpose of the script is, and also makes the `force` flag unclear.
- What's "normalization"?
- How do I get the info for my InfluxDB instance (e.g., port and host)?
- Include a link to the documentation for how to get your account token.
- What is Berkeley DB?
- What is the shelve module of Python?
- What is the purpose of the history_downloader_settings file? Can I modify it?

**Comment by perusio** [comment]
Use punctuation in your code comments. It is prose to be read by humans.
